Imported GCC 15.2 via populate.sh

diff --git a/ccache/misc/clang-format b/ccache/misc/clang-format
--- a/ccache/misc/clang-format
+++ b/ccache/misc/clang-format
@@ -15,25 +15,25 @@ if [ -n "${CLANG_FORMAT:-}" ]; then
     exec "$CLANG_FORMAT" "$@"
 fi
 
-top_dir="$(dirname "$0")"
-clang_format_exe="$top_dir/.clang-format-exe"
-clang_format_version=11
-clang_format_release=master-1d7ec53d
+misc_dir="$(dirname "$0")"
+clang_format_exe="${misc_dir}/.clang-format-exe"
+clang_format_version=18
+clang_format_release=master-609f1513
 url_prefix="https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/${clang_format_release}/clang-format-${clang_format_version}_"
 
 if [ ! -x "$clang_format_exe" ]; then
     case "$(uname -s | tr '[:upper:]' '[:lower:]')" in
         *mingw*|*cygwin*|*msys*)
             url_suffix=windows-amd64.exe
-            checksum=7167f201acbd8ff06a7327d14db0d8a169393384bbc42873bb8277b788cc4469
+            checksum=d8c788f0d983177ae2ebcac6cb32d0e9bd79f93bae5aab5197b1d5998be4f90b
             ;;
         *darwin*)
             url_suffix=macosx-amd64
-            checksum=0cab857e66aa9ed9ea00eee3c94bfc91a2d72ab440327e15784852cf94b1814b
+            checksum=de1a6affc3253af8cf48130d2940375b284025bedbb2b812d55e85cfdff69e83
             ;;
         *linux*)
             url_suffix=linux-amd64
-            checksum=a9d76e3275823ea308bc2e4d2a6e3cc693f38c29d891f1d74cb0e1553e698dea
+            checksum=2a6cd633f85e96a32f68cca3f1ac2ef63c677cae0f2b2a7f2a0c3f81a36a2353
             ;;
         *)
             echo "Error: Please set CLANG_FORMAT to clang-format version $clang_format_version" >&2
@@ -54,8 +54,8 @@ if [ ! -x "$clang_format_exe" ]; then
 
     if ! command -v sha256sum >/dev/null; then
         echo "Warning: sha256sum not found, not verifying clang-format integrity" >&2
-    elif ! echo "$checksum $clang_format_exe.tmp" | sha256sum --status -c; then
-        echo "Error: Bad checksum of downloaded clang-format" >&2
+    elif ! echo "$checksum $clang_format_exe.tmp" | sha256sum --status -c -; then
+        echo "Error: Bad checksum of downloaded clang-format: expected ${checksum}, actual $(sha256sum ${clang_format_exe}.tmp | awk '{print $1}')" >&2
         exit 1
     fi
 
diff --git a/gdb/gdb/gcore.in b/gdb/gdb/gcore.in
--- a/gdb/gdb/gcore.in
+++ b/gdb/gdb/gcore.in
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#   Copyright (C) 2003-2024 Free Software Foundation, Inc.
+#   Copyright (C) 2003-2025 Free Software Foundation, Inc.
 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -20,6 +20,9 @@
 # It starts up gdb, attaches to the given PID and invokes the gcore command.
 #
 
+PKGVERSION="(GDB) "
+VERSION="@VERSION@"
+
 # Need to check for -o option, but set default basename to "core".
 prefix=core
 
@@ -27,8 +30,47 @@ prefix=core
 # to ensure gdb dumps all mappings (OS dependent).
 dump_all_cmds=()
 
-while getopts :ao: opt; do
-    case "$opt" in
+data_directory_opt=()
+
+function print_usage() {
+    prefix="Usage: $0"
+    padding=$(printf '%*s' ${#prefix})
+
+    echo "$prefix [-h|--help] [-v|--version]"
+    echo "$padding [-a] [-o prefix] [-d data-directory]"
+    echo "$padding pid1 [pid2...pidN]"
+}
+
+function print_try_help() {
+    echo "Try '$0 --help' for more information."
+}
+
+function print_help() {
+    print_usage
+    echo
+    echo "Create a core file of a running program using GDB."
+    echo
+    echo "  -h, --help         Print this message then exit."
+    echo "  -v, --version      Print version information then exit."
+    echo "  -a                 Dump all memory mappings."
+    echo "  -o prefix          Use 'prefix.pid' as the core file name."
+    echo "                       The default prefix is 'core'."
+    echo "  -d dir             Pass '--data-directory dir' as an argument"
+    echo "                       to GDB."
+}
+
+function print_version() {
+    echo "GNU gcore (${PKGVERSION}) ${VERSION}"
+}
+
+while getopts vhao:d:-: OPT; do
+    if [ "$OPT" = "-" ]; then
+	OPT="${OPTARG%%=*}"
+	OPTARG="${OPTARG#'$OPT'}"
+	OPTARG="${OPTARG#=}"
+    fi
+
+    case "$OPT" in
         a)
             case "$OSTYPE" in
                 linux*)
@@ -40,9 +82,29 @@ while getopts :ao: opt; do
         o)
             prefix=$OPTARG
             ;;
+        d)
+            data_directory_opt=("--data-directory" "$OPTARG")
+            ;;
+	h | help)
+	    print_help
+	    exit 0
+	    ;;
+	v | version)
+	    print_version
+	    exit 0
+	    ;;
+	\?)
+	    # getopts has already output an error message.
+	    print_try_help 1>&2
+	    exit 2
+	    ;;
         *)
-            echo "usage:  @GCORE_TRANSFORM_NAME@ [-a] [-o prefix] pid1 [pid2...pidN]"
-            exit 2
+	    # Unknown single character options are handled by the \?
+	    # case above.  This is formatted to match the error
+	    # getopts gives for an unknown single character option.
+	    echo "$0: illegal option -- $OPT" 1>&2
+	    print_try_help 1>&2
+	    exit 2
             ;;
     esac
 done
@@ -51,8 +113,8 @@ shift $((OPTIND-1))
 
 if [ "$#" -eq "0" ]
 then
-    echo "usage:  @GCORE_TRANSFORM_NAME@ [-a] [-o prefix] pid1 [pid2...pidN]"
-    exit 2
+    print_usage 1>&2
+    exit 1
 fi
 
 # Attempt to fetch the absolute path to the gcore script that was
@@ -84,8 +146,8 @@ fi
 
 # Check if the GDB binary is in the expected path.  If not, just
 # quit with a message.
-if [ ! -f "$binary_path/@GDB_TRANSFORM_NAME@" ]; then
-  echo "gcore: GDB binary (${binary_path}/@GDB_TRANSFORM_NAME@) not found"
+if [ ! -f "$binary_path/i386-pc-linux-gnu-gdb" ]; then
+  echo "gcore: GDB binary (${binary_path}/i386-pc-linux-gnu-gdb) not found"
   exit 1
 fi
 
@@ -97,7 +159,8 @@ for pid in "$@"
 do
 	# `</dev/null' to avoid touching interactive terminal if it is
 	# available but not accessible as GDB would get stopped on SIGTTIN.
-	"$binary_path/@GDB_TRANSFORM_NAME@" </dev/null \
+	"$binary_path/i386-pc-linux-gnu-gdb" </dev/null \
+            "${data_directory_opt[@]}" \
 	    --nx --batch --readnever -iex 'set debuginfod enabled off' \
 	    -ex "set pagination off" -ex "set height 0" -ex "set width 0" \
 	    "${dump_all_cmds[@]}" \
@@ -106,7 +169,7 @@ do
 	if [ -r "$prefix.$pid" ] ; then
 	    rc=0
 	else
-	    echo "@GCORE_TRANSFORM_NAME@: failed to create $prefix.$pid"
+	    echo "i386-pc-linux-gnu-gcore: failed to create $prefix.$pid"
 	    rc=1
 	    break
 	fi
